### ISSUE TITLE
Unwanted output

### ISSUE THREAD

**Issue by josenobile** [zouhir/lqip-loader#12]
When executed it produces this output:
VIPS-INFO: 8 point mask
VIPS-INFO: reducev sequential line cache
VIPS-INFO: 7 point mask

Could you please remove any output to stdout ?

**Comment by lovell** [comment]
Cross-posted at https://github.com/lovell/sharp/issues/1144 - @josenobile please don't do this.

**Comment by josenobile** [comment]
Hi, The issue happen in both proyects.
