### ISSUE TITLE
Should 'lqip' be a dependency instead of a devDependency?

### ISSUE THREAD

**Issue by wlingke** [zouhir/lqip-loader#15]
In order to run `lqip-loader`, I have to have `lqip` installed. `yarn add lqip-loader --dev` won't install `lqip` because it's not listed as an actual dependency.

I think `lqip` should probably be a dependency because well... it kind of is :)

**Comment by zouhir** [comment]
yes.

**Comment by zouhir** [comment]
I will do that!
