### ISSUE TITLE
Publish v2.1.0

### ISSUE THREAD

**Issue by wlingke** [zouhir/lqip-loader#16]
Can you please publish lqip-loader v2.1.0 to NPM so it can be easily installed? Thanks!

**Comment by tothandras** [comment]
@zouhir I'm not sure what's the status of the project, but this would be great and I assume it takes like 5 seconds. 🙂 Thanks!

**Comment by zouhir** [comment]
I just publushed 2.1.0! sorry guys I am falling behind on keeping up with OSS as I've recently relocated to a new country!
