### ISSUE TITLE
Can this loader be chained with file loader/url loader?

### ISSUE THREAD

**Issue by mike3run** [zouhir/lqip-loader#7]
🙏

**Comment by mike3run** [comment]
I recently saw this loader:

https://github.com/EmilTholin/image-trace-loader

That can be chained, maybe the way they're doing it can help bring some light on how to do it?

I've never done a webpack plugin of any sorts so I'm a bit in the darkness but trying to help as much as i can 😄

**Comment by zouhir** [comment]
released v2.1.0!!
